package com.phrasecards.app;
import android.app.*;import android.os.*;import android.content.*;import android.content.res.Configuration;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.view.animation.*;import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;import androidx.appcompat.app.AppCompatDelegate;import org.json.*;import java.util.*;import java.io.*;

public class MainActivity extends AppCompatActivity{
 static class Card{String id,lang,p,en,fa,n,e;Card(String a,String b,String c,String d,String f,String g,String h){id=a;lang=b;p=c;en=d;fa=f;n=g;e=h;}}
 ArrayList<Card>cards=new ArrayList<>(),dailyCards=new ArrayList<>();ArrayList<String>decks=new ArrayList<>();
 SharedPreferences sp;Card cur;String lang="English";int currentPos=0,dailyIndex=0,dailyGood=0,dailyHard=0;boolean dailyMode=false;
 TextView title,currentLanguage,phrase,enMeaning,faMeaning,note,ex,stats,cardNumber;LinearLayout ans,rating,studyArea;View goodBar,hardBar,unseenBar;
 Button menuButton,daily,show,hard,good,add,manage;float downX,downY;static final int EXPORT_CSV=301,IMPORT_CSV=302;

 public void onCreate(Bundle b){sp=getSharedPreferences("phrasecards_v7",MODE_PRIVATE);applyTheme();super.onCreate(b);setContentView(R.layout.activity_main);bind();loadSeed();loadCustom();loadDecks();styleForTheme();
  menuButton.setOnClickListener(v->showMainMenu());show.setOnClickListener(v->{ans.setVisibility(View.VISIBLE);show.setVisibility(View.GONE);rating.setVisibility(View.VISIBLE);});
  hard.setOnClickListener(v->rate(false));good.setOnClickListener(v->rate(true));add.setOnClickListener(v->addDialog());manage.setOnClickListener(v->manageDialog());daily.setOnClickListener(v->startDaily());
  studyArea.setOnTouchListener((v,event)->{if(event.getAction()==MotionEvent.ACTION_DOWN){downX=event.getX();downY=event.getY();return true;}if(event.getAction()==MotionEvent.ACTION_UP&&!dailyMode){float dx=event.getX()-downX,dy=event.getY()-downY;if(Math.abs(dx)>120&&Math.abs(dx)>Math.abs(dy)){currentPos+=dx>0?-1:1;next();return true;}}return true;});next();}
 void applyTheme(){String t=sp.getString("theme","light");AppCompatDelegate.setDefaultNightMode(t.equals("dark")?AppCompatDelegate.MODE_NIGHT_YES:AppCompatDelegate.MODE_NIGHT_NO);}
 void bind(){title=findViewById(R.id.title);currentLanguage=findViewById(R.id.currentLanguage);phrase=findViewById(R.id.phrase);enMeaning=findViewById(R.id.meaningEnglish);faMeaning=findViewById(R.id.meaningPersian);note=findViewById(R.id.note);ex=findViewById(R.id.example);stats=findViewById(R.id.stats);cardNumber=findViewById(R.id.cardNumber);ans=findViewById(R.id.answerBox);rating=findViewById(R.id.rating);studyArea=findViewById(R.id.studyArea);goodBar=findViewById(R.id.goodProgress);hardBar=findViewById(R.id.hardProgress);unseenBar=findViewById(R.id.unseenProgress);menuButton=findViewById(R.id.menuButton);daily=findViewById(R.id.daily);show=findViewById(R.id.show);hard=findViewById(R.id.hard);good=findViewById(R.id.good);add=findViewById(R.id.add);manage=findViewById(R.id.manage);}
 void styleForTheme(){boolean dark=(getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES;if(dark){int bg=Color.rgb(18,18,18),fg=Color.rgb(238,238,238),btn=Color.rgb(55,55,55);findViewById(R.id.root).setBackgroundColor(bg);studyArea.setBackgroundColor(Color.rgb(28,28,28));title.setTextColor(fg);currentLanguage.setTextColor(fg);phrase.setTextColor(fg);enMeaning.setTextColor(fg);faMeaning.setTextColor(fg);note.setTextColor(fg);ex.setTextColor(fg);stats.setTextColor(Color.LTGRAY);cardNumber.setTextColor(Color.LTGRAY);menuButton.setBackgroundTintList(android.content.res.ColorStateList.valueOf(btn));menuButton.setTextColor(fg);show.setBackgroundTintList(android.content.res.ColorStateList.valueOf(btn));show.setTextColor(fg);add.setBackgroundTintList(android.content.res.ColorStateList.valueOf(btn));add.setTextColor(fg);manage.setBackgroundTintList(android.content.res.ColorStateList.valueOf(btn));manage.setTextColor(fg);}}
 boolean hasPersian(String s){for(char c:s.toCharArray())if(c>=0x0600&&c<=0x06FF)return true;return false;}
 void loadSeed(){try{InputStream in=getAssets().open("seed_cards.json");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();JSONArray a=new JSONArray(out.toString("UTF-8"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);String id=o.getString("id");if(sp.getBoolean(id+"_deleted",false))continue;String raw=o.optString("tr"),en="",fa="";if(hasPersian(raw))fa=raw;else en=raw;cards.add(new Card(id,o.getString("lang"),o.getString("phrase"),en,fa,o.optString("note"),o.optString("ex")));}}catch(Exception e){e.printStackTrace();}}
 void loadCustom(){try{JSONArray a=new JSONArray(sp.getString("customCards","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);cards.add(new Card(o.getString("id"),o.getString("lang"),o.getString("p"),o.optString("en"),o.optString("fa"),o.optString("n"),o.optString("e")));}}catch(Exception ignored){}}
 void saveCustom(){JSONArray a=new JSONArray();try{for(Card c:cards)if(c.id.startsWith("c")){JSONObject o=new JSONObject();o.put("id",c.id);o.put("lang",c.lang);o.put("p",c.p);o.put("en",c.en);o.put("fa",c.fa);o.put("n",c.n);o.put("e",c.e);a.put(o);}}catch(Exception ignored){}sp.edit().putString("customCards",a.toString()).apply();}
 void loadDecks(){decks.add("English");decks.add("Norwegian");try{JSONArray a=new JSONArray(sp.getString("decks","[]"));for(int i=0;i<a.length();i++){String d=a.getString(i);if(!decks.contains(d))decks.add(d);}}catch(Exception ignored){}}
 void saveDecks(){JSONArray a=new JSONArray();for(String d:decks)if(!d.equals("English")&&!d.equals("Norwegian"))a.put(d);sp.edit().putString("decks",a.toString()).apply();}

 void showMainMenu(){final String[]items={"Switch language","Add new language","Import CSV","Export active language to CSV","Dark mode","Light mode"};new AlertDialog.Builder(this).setTitle("Menu").setItems(items,(d,w)->{if(w==0)chooseLanguage();else if(w==1)addLanguage();else if(w==2)importCsv();else if(w==3)exportCsv();else if(w==4)setTheme("dark");else setTheme("light");}).show();}
 void chooseLanguage(){String[]a=decks.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Switch language").setSingleChoiceItems(a,decks.indexOf(lang),(d,w)->{lang=decks.get(w);currentPos=0;d.dismiss();next();}).show();}
 void addLanguage(){EditText i=new EditText(this);i.setHint("e.g. German");new AlertDialog.Builder(this).setTitle("Add new language").setView(i).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,x)->{String n=i.getText().toString().trim();if(!n.isEmpty()&&!decks.contains(n)){decks.add(n);saveDecks();lang=n;currentPos=0;next();}}).show();}
 void setTheme(String t){sp.edit().putString("theme",t).apply();applyTheme();recreate();}

 int box(Card c){return sp.getInt(c.id+"_box",1);}long due(Card c){return sp.getLong(c.id+"_due",0);}int result(Card c){return sp.getInt(c.id+"_result",0);}long interval(int b){long d=86400000L;return b<=1?0:b==2?d:b==3?3*d:b==4?7*d:14*d;}
 ArrayList<Card>ordered(){ArrayList<Card>a=new ArrayList<>();for(Card c:cards)if(c.lang.equals(lang))a.add(c);Collections.sort(a,(x,y)->{int z=Integer.compare(box(x),box(y));return z!=0?z:Long.compare(due(x),due(y));});return a;}
 void next(){currentLanguage.setText("Language: "+lang);if(dailyMode){showDaily();return;}ArrayList<Card>a=ordered();if(a.isEmpty()){cur=null;phrase.setText("No cards yet");cardNumber.setText("");update();return;}if(currentPos>=a.size())currentPos=0;if(currentPos<0)currentPos=a.size()-1;cur=a.get(currentPos);showCard("Card "+(currentPos+1)+" of "+a.size()+" • Box "+box(cur));}
 void showCard(String number){phrase.setText(cur.p);enMeaning.setText(cur.en.isEmpty()?"—":cur.en);faMeaning.setText(cur.fa.isEmpty()?"—":cur.fa);note.setText(cur.n.isEmpty()?"—":cur.n);ex.setText(cur.e.isEmpty()?"—":cur.e.replaceFirst("^Example:\\s*",""));cardNumber.setText(number);ans.setVisibility(View.GONE);rating.setVisibility(View.GONE);show.setVisibility(View.VISIBLE);studyArea.setAlpha(0f);studyArea.setTranslationX(40f);studyArea.animate().alpha(1f).translationX(0).setDuration(180).setInterpolator(new DecelerateInterpolator()).start();update();}
 void rate(boolean ok){if(cur==null)return;int b=ok?Math.min(5,box(cur)+1):1;sp.edit().putInt(cur.id+"_box",b).putLong(cur.id+"_due",System.currentTimeMillis()+interval(b)).putInt(cur.id+"_result",ok?1:-1).apply();if(dailyMode){if(ok)dailyGood++;else{dailyHard++;sp.edit().putLong(cur.id+"_dailyHard",dayKey()).apply();}dailyIndex++;showDaily();}else{currentPos++;next();}}
 long dayKey(){Calendar c=Calendar.getInstance();return c.get(Calendar.YEAR)*1000L+c.get(Calendar.DAY_OF_YEAR);}
 void startDaily(){dailyCards.clear();dailyGood=0;dailyHard=0;dailyIndex=0;long y=dayKey()-1;ArrayList<Card>h=new ArrayList<>(),o=new ArrayList<>();for(Card c:cards)if(c.lang.equals(lang)){if(sp.getLong(c.id+"_dailyHard",-99)==y)h.add(c);else o.add(c);}Collections.shuffle(o);dailyCards.addAll(h);for(Card c:o)if(dailyCards.size()<10)dailyCards.add(c);while(dailyCards.size()>10)dailyCards.remove(dailyCards.size()-1);if(dailyCards.isEmpty()){Toast.makeText(this,"No cards",Toast.LENGTH_SHORT).show();return;}dailyMode=true;showDaily();}
 void showDaily(){if(dailyIndex>=dailyCards.size()){dailyMode=false;daily.setText("Daily Practice");new AlertDialog.Builder(this).setTitle("Daily Practice Complete").setMessage("Good: "+dailyGood+"\nHard: "+dailyHard+"\n\nHard cards are prioritized tomorrow.").setPositiveButton("Done",(d,x)->next()).show();return;}cur=dailyCards.get(dailyIndex);daily.setText("Daily "+(dailyIndex+1)+"/"+dailyCards.size());showCard("Daily card "+(dailyIndex+1)+" of "+dailyCards.size()+" • Box "+box(cur));}
 void update(){int total=0,g=0,h=0;for(Card c:cards)if(c.lang.equals(lang)){total++;if(result(c)==1)g++;else if(result(c)==-1)h++;}int u=Math.max(0,total-g-h);weight(goodBar,g);weight(hardBar,h);weight(unseenBar,u);stats.setText("Good "+g+" • Hard "+h+" • Unreviewed "+u+" • Total "+total);}
 void weight(View v,int w){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.weight=Math.max(0,w);p.width=0;v.setLayoutParams(p);}

 LinearLayout form(){LinearLayout l=new LinearLayout(this);l.setPadding(28,0,28,0);l.setOrientation(LinearLayout.VERTICAL);String[]h={"Phrase","English meaning","معنی فارسی","Usage","Example"};for(String z:h){EditText x=new EditText(this);x.setHint(z);l.addView(x);}return l;}
 void addDialog(){LinearLayout l=form();new AlertDialog.Builder(this).setTitle("Add card to "+lang).setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,x)->{String p=((EditText)l.getChildAt(0)).getText().toString().trim();if(!p.isEmpty()){cards.add(new Card("c"+System.currentTimeMillis(),lang,p,((EditText)l.getChildAt(1)).getText().toString(),((EditText)l.getChildAt(2)).getText().toString(),((EditText)l.getChildAt(3)).getText().toString(),((EditText)l.getChildAt(4)).getText().toString()));saveCustom();next();}}).show();}
 void manageDialog(){ArrayList<Card>l=new ArrayList<>();for(Card c:cards)if(c.lang.equals(lang))l.add(c);String[]n=new String[l.size()];for(int i=0;i<n.length;i++)n[i]="Box "+box(l.get(i))+" • "+l.get(i).p;new AlertDialog.Builder(this).setTitle(lang+" — "+l.size()+" cards").setItems(n,(d,i)->cardActions(l.get(i))).setNegativeButton("Close",null).show();}
 void cardActions(Card c){new AlertDialog.Builder(this).setTitle(c.p).setItems(new String[]{"Delete card","Reset Leitner progress"},(d,w)->{if(w==0)new AlertDialog.Builder(this).setTitle("Delete card?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(q,x)->{cards.remove(c);sp.edit().putBoolean(c.id+"_deleted",true).apply();saveCustom();next();}).show();else{sp.edit().remove(c.id+"_box").remove(c.id+"_due").remove(c.id+"_result").apply();next();}}).show();}

 void exportCsv(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"phrase_cards_"+lang.toLowerCase()+".csv");startActivityForResult(i,EXPORT_CSV);}
 void importCsv(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("text/*");startActivityForResult(i,IMPORT_CSV);}
 String esc(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK||data==null)return;try{Uri u=data.getData();if(r==EXPORT_CSV){BufferedWriter w=new BufferedWriter(new OutputStreamWriter(getContentResolver().openOutputStream(u),"UTF-8"));w.write("language,phrase,meaning_english,meaning_persian,usage,example,leitner_box\n");int count=0;for(Card x:cards)if(x.lang.equals(lang)){w.write(esc(x.lang)+","+esc(x.p)+","+esc(x.en)+","+esc(x.fa)+","+esc(x.n)+","+esc(x.e)+","+box(x)+"\n");count++;}w.close();Toast.makeText(this,count+" "+lang+" cards exported",Toast.LENGTH_LONG).show();}else{BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u),"UTF-8"));String line;int count=0;boolean firstNonBlank=true;while((line=br.readLine())!=null){if(line.trim().isEmpty())continue;ArrayList<String>a=parseCsv(line);if(firstNonBlank){firstNonBlank=false;if(isHeader(a))continue;}if(a.size()<2)continue;String phrase=a.get(0).trim();if(phrase.isEmpty())continue;String en="",fa="",example="";if(a.size()>=4){en=a.get(1).trim();fa=a.get(2).trim();example=a.get(3).trim();}else{String meaning=a.get(1).trim();if(hasPersian(meaning))fa=meaning;else en=meaning;}cards.add(new Card("c"+System.currentTimeMillis()+"_"+count,lang,phrase,en,fa,"",example));count++;}br.close();saveCustom();Toast.makeText(this,count+" cards imported into "+lang,Toast.LENGTH_LONG).show();next();}}catch(Exception e){new AlertDialog.Builder(this).setTitle("CSV error").setMessage(String.valueOf(e.getMessage())).setPositiveButton("OK",null).show();}}
 boolean isHeader(ArrayList<String>a){if(a.size()<2)return false;String x=a.get(0).trim().toLowerCase(),y=a.get(1).trim().toLowerCase();return x.equals("phrase")&&(y.contains("meaning")||y.equals("translation"));}
 ArrayList<String>parseCsv(String s){ArrayList<String>a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='"'){b.append('"');i++;}else q=!q;}else if(c==','&&!q){a.add(b.toString());b.setLength(0);}else b.append(c);}a.add(b.toString());return a;}
}