package com.phrasecards.app;
import android.app.*;import android.os.*;import android.os.VibrationEffect;import android.os.Vibrator;import android.content.*;import android.content.res.Configuration;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.graphics.drawable.ColorDrawable;import android.net.Uri;import android.text.*;import android.view.*;import android.view.animation.*;import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;import android.speech.tts.TextToSpeech;import android.speech.tts.Voice;import androidx.appcompat.app.AppCompatDelegate;import org.json.*;import java.util.*;import java.io.*;

public class MainActivity extends AppCompatActivity{
 static class Card{String id,lang,p,en,fa,n,e;Card(String a,String b,String c,String d,String f,String g,String h){id=a;lang=b;p=c;en=d;fa=f;n=g;e=h;}}
 ArrayList<Card>cards=new ArrayList<>(),dailyCards=new ArrayList<>();ArrayList<String>decks=new ArrayList<>();HashSet<String>selected=new HashSet<>();
 SharedPreferences sp;Card cur;String lang="English",query="";int dailyIndex=0,dailyGood=0,dailyHard=0;boolean dailyMode=false,dark=false;boolean filterFavorites=false;String filterTag="";
 LinearLayout libraryView,practiceView,answerBox,rating,studyArea,selectionBar;GridLayout cardGrid;
 TextView title,currentLanguage,cardCount,stats,goodStats,hardStats,selectedCount,practiceProgress,phrase,enMeaning,faMeaning,example; View splash;
 EditText search;ImageButton filterButton;View goodBar,hardBar,unseenBar,drawerOverlay,drawerPanel;Button menuButton,daily,add,show,hard,good,backLibrary,selectAll,deleteSelected,moveSelected,cancelSelection,drawerLanguage,drawerAddLanguage,drawerImport,drawerExport,drawerBoxes,drawerReset,drawerMode,drawerVoice,drawerNotification,drawerAbout,drawerClose; ImageButton practiceListen;
 static final int EXPORT_CSV=401,IMPORT_CSV=402; TextToSpeech tts;boolean ttsReady=false;

 public void onCreate(Bundle b){sp=getSharedPreferences("zope_flashcards_v81",MODE_PRIVATE);applyTheme();super.onCreate(b);setContentView(R.layout.activity_main);bind();title.setText("Zope Flash Cards v"+appVersion());cleanDatabaseOnce();loadSeed();loadCustom();loadDecks();lang=sp.getString("active_language","English");if(!decks.contains(lang))lang="English";loadFilter();dark=isDark();styleTheme();findViewById(R.id.mainBottomBar).setBackgroundColor(Color.TRANSPARENT);styleMainButton(add);styleMainButton(daily);wire();initTts();renderLibrary();NotificationScheduler.ensureScheduled(this);handleNotificationIntent(getIntent());splash=findViewById(R.id.splash);splash.postDelayed(()->splash.setVisibility(View.GONE),550);}
 void applyTheme(){String t=sp.getString("theme","system");int m=t.equals("dark")?AppCompatDelegate.MODE_NIGHT_YES:t.equals("light")?AppCompatDelegate.MODE_NIGHT_NO:AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM;if(AppCompatDelegate.getDefaultNightMode()!=m)AppCompatDelegate.setDefaultNightMode(m);}
 boolean isDark(){return (getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES;}
 void bind(){libraryView=findViewById(R.id.libraryView);practiceView=findViewById(R.id.practiceView);answerBox=findViewById(R.id.answerBox);rating=findViewById(R.id.rating);studyArea=findViewById(R.id.studyArea);selectionBar=findViewById(R.id.selectionBar);cardGrid=findViewById(R.id.cardGrid);title=findViewById(R.id.title);currentLanguage=findViewById(R.id.currentLanguage);cardCount=findViewById(R.id.cardCount);stats=findViewById(R.id.stats);goodStats=findViewById(R.id.goodStats);hardStats=findViewById(R.id.hardStats);selectedCount=findViewById(R.id.selectedCount);practiceProgress=findViewById(R.id.practiceProgress);phrase=findViewById(R.id.phrase);enMeaning=findViewById(R.id.meaningEnglish);faMeaning=findViewById(R.id.meaningPersian);example=findViewById(R.id.example);search=findViewById(R.id.search);filterButton=findViewById(R.id.filterButton);goodBar=findViewById(R.id.goodProgress);hardBar=findViewById(R.id.hardProgress);unseenBar=findViewById(R.id.unseenProgress);menuButton=findViewById(R.id.menuButton);daily=findViewById(R.id.daily);add=findViewById(R.id.add);show=findViewById(R.id.show);hard=findViewById(R.id.hard);good=findViewById(R.id.good);backLibrary=findViewById(R.id.backLibrary);deleteSelected=findViewById(R.id.deleteSelected);selectAll=findViewById(R.id.selectAll);moveSelected=findViewById(R.id.moveSelected);cancelSelection=findViewById(R.id.cancelSelection);practiceListen=findViewById(R.id.practiceListen);drawerOverlay=findViewById(R.id.drawerOverlay);drawerPanel=findViewById(R.id.drawerPanel);drawerLanguage=findViewById(R.id.drawerLanguage);drawerAddLanguage=findViewById(R.id.drawerAddLanguage);drawerImport=findViewById(R.id.drawerImport);drawerExport=findViewById(R.id.drawerExport);drawerBoxes=findViewById(R.id.drawerBoxes);drawerReset=findViewById(R.id.drawerReset);drawerMode=findViewById(R.id.drawerMode);drawerVoice=findViewById(R.id.drawerVoice);drawerNotification=findViewById(R.id.drawerNotification);drawerAbout=findViewById(R.id.drawerAbout);drawerClose=findViewById(R.id.drawerClose);}
 void wire(){menuButton.setOnClickListener(v->showMenu());drawerOverlay.setOnClickListener(v->closeMenu());drawerPanel.setOnClickListener(v->{});drawerClose.setOnClickListener(v->closeMenu());drawerLanguage.setOnClickListener(v->{closeMenu();chooseLanguage();});drawerAddLanguage.setOnClickListener(v->{closeMenu();addLanguage();});drawerImport.setOnClickListener(v->{closeMenu();importCsv();});drawerExport.setOnClickListener(v->{closeMenu();exportCsv();});drawerBoxes.setOnClickListener(v->{closeMenu();viewByBox();});drawerReset.setOnClickListener(v->{closeMenu();resetLeitner();});drawerMode.setOnClickListener(v->{closeMenu();chooseMode();});drawerVoice.setOnClickListener(v->{closeMenu();voiceSettings();});drawerNotification.setOnClickListener(v->{closeMenu();notificationSettings();});drawerAbout.setOnClickListener(v->{closeMenu();showAbout();});practiceListen.setOnClickListener(v->{if(cur!=null)speakPhrase(cur);});daily.setOnClickListener(v->startDaily());filterButton.setOnClickListener(v->showFilterDialog());add.setOnClickListener(v->editDialog(null));show.setOnClickListener(v->{answerBox.setVisibility(View.VISIBLE);show.setVisibility(View.GONE);rating.setVisibility(View.VISIBLE);});hard.setOnClickListener(v->rate(false));good.setOnClickListener(v->rate(true));backLibrary.setOnClickListener(v->leavePractice());selectAll.setOnClickListener(v->toggleSelectAll());deleteSelected.setOnClickListener(v->deleteSelected());moveSelected.setOnClickListener(v->moveSelected());cancelSelection.setOnClickListener(v->{selected.clear();renderLibrary();});search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){query=s.toString().trim().toLowerCase();updateSelectAllLabel();renderGrid();}public void afterTextChanged(Editable e){}});}
 void styleTheme(){dark=isDark();int bg=dark?Color.rgb(18,18,18):Color.rgb(250,250,250),fg=dark?Color.rgb(240,240,240):Color.rgb(25,25,25),panel=dark?Color.rgb(30,30,30):Color.WHITE;findViewById(R.id.root).setBackgroundColor(bg);findViewById(R.id.mainBottomBar).setBackgroundColor(Color.TRANSPARENT);libraryView.setBackgroundColor(bg);practiceView.setBackgroundColor(bg);studyArea.setBackgroundColor(panel);title.setTextColor(fg);currentLanguage.setTextColor(fg);cardCount.setTextColor(fg);stats.setTextColor(dark?Color.LTGRAY:Color.DKGRAY);goodStats.setTextColor(Color.rgb(22,163,74));hardStats.setTextColor(Color.rgb(220,38,38));drawerPanel.setBackgroundColor(panel);phrase.setTextColor(fg);enMeaning.setTextColor(fg);faMeaning.setTextColor(fg);example.setTextColor(fg);practiceProgress.setTextColor(fg);selectedCount.setTextColor(fg);styleMainActionButton(add);styleMainActionButton(daily);styleMainActionButton(show);if(filterButton!=null)updateFilterVisual();}
 boolean hasPersian(String s){for(char c:s.toCharArray())if(c>=0x0600&&c<=0x06FF)return true;return false;}
 void styleMainActionButton(Button b){if(b==null)return;b.setBackgroundTintList(null);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(214,196,77));g.setCornerRadius(dp(26));b.setBackground(g);b.setTextColor(Color.rgb(20,20,20));b.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);b.setAllCaps(false);}
 void cleanDatabaseOnce(){if(sp.getBoolean("db_clean_v94",false))return;SharedPreferences.Editor ed=sp.edit();ed.putString("customCards","[]");for(String k:new ArrayList<String>(sp.getAll().keySet()))if(k.endsWith("_box")||k.endsWith("_due")||k.endsWith("_result")||k.endsWith("_dailyHard")||k.endsWith("_favorite")||k.endsWith("_deleted"))ed.remove(k);ed.putBoolean("db_clean_v94",true);ed.apply();}

 void loadSeed(){try{InputStream in=getAssets().open("seed_cards.json");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();JSONArray a=new JSONArray(out.toString("UTF-8"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);String id=o.getString("id");if(sp.getBoolean(id+"_deleted",false))continue;String raw=o.optString("tr"),en="",fa="";if(hasPersian(raw))fa=raw;else en=raw;cards.add(new Card(id,o.getString("lang"),o.getString("phrase"),en,fa,o.optString("note"),o.optString("ex")));}}catch(Exception e){e.printStackTrace();}}
 void loadCustom(){try{JSONArray a=new JSONArray(sp.getString("customCards","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);cards.add(new Card(o.getString("id"),o.getString("lang"),o.getString("p"),o.optString("en"),o.optString("fa"),o.optString("n"),o.optString("e")));}}catch(Exception ignored){}}
 void saveCustom(){JSONArray a=new JSONArray();try{for(Card c:cards)if(c.id.startsWith("c")){JSONObject o=new JSONObject();o.put("id",c.id);o.put("lang",c.lang);o.put("p",c.p);o.put("en",c.en);o.put("fa",c.fa);o.put("n",c.n);o.put("e",c.e);a.put(o);}}catch(Exception ignored){}sp.edit().putString("customCards",a.toString()).apply();}
 void loadDecks(){decks.add("English");decks.add("Norwegian");try{JSONArray a=new JSONArray(sp.getString("decks","[]"));for(int i=0;i<a.length();i++){String d=a.getString(i);if(!decks.contains(d))decks.add(d);}}catch(Exception ignored){}}
 void saveDecks(){JSONArray a=new JSONArray();for(String d:decks)if(!d.equals("English")&&!d.equals("Norwegian"))a.put(d);sp.edit().putString("decks",a.toString()).apply();}
 int box(Card c){return sp.getInt(c.id+"_box",1);}int result(Card c){return sp.getInt(c.id+"_result",0);}long interval(int b){long d=86400000L;return b<=1?0:b==2?d:b==3?3*d:b==4?7*d:14*d;}
 boolean favorite(Card c){return sp.getBoolean(c.id+"_favorite",false);} boolean matchesFilter(Card c){if(filterFavorites&&!favorite(c))return false;if(!filterTag.isEmpty()&&!c.n.trim().equalsIgnoreCase(filterTag.trim()))return false;return true;}
 ArrayList<Card>active(){ArrayList<Card>a=new ArrayList<>();for(Card c:cards)if(c.lang.equals(lang)&&matchesFilter(c))a.add(c);Collections.sort(a,(a1,a2)->Boolean.compare(favorite(a2),favorite(a1)));return a;}
 void renderLibrary(){libraryView.setVisibility(View.VISIBLE);practiceView.setVisibility(View.GONE);dailyMode=false;currentLanguage.setText(lang);ArrayList<Card>a=active();cardCount.setText(a.size()+" cards");updateStats();selectionBar.setVisibility(selected.isEmpty()?View.GONE:View.VISIBLE);selectedCount.setText(selected.size()+" selected");updateSelectAllLabel();renderGrid();}
 void renderGrid(){cardGrid.removeAllViews();ArrayList<Card>a=active();int shown=0;for(int i=0;i<a.size();i++){Card c=a.get(i);if(!query.isEmpty()&&!c.p.toLowerCase().contains(query)&&!c.en.toLowerCase().contains(query)&&!c.fa.toLowerCase().contains(query)&&!c.n.toLowerCase().contains(query))continue;shown++;cardGrid.addView(tile(c,i+1),tileParams());}if(shown==0){TextView empty=new TextView(this);empty.setText(query.isEmpty()?"No cards yet":"No matching cards");empty.setGravity(Gravity.CENTER);empty.setPadding(10,40,10,40);empty.setTextColor(dark?Color.LTGRAY:Color.DKGRAY);GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.columnSpec=GridLayout.spec(0,3,1f);p.width=0;p.height=GridLayout.LayoutParams.WRAP_CONTENT;cardGrid.addView(empty,p);}}
 GridLayout.LayoutParams tileParams(){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(116);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(3),dp(3),dp(3),dp(3));return p;}
 View tile(Card c,int number){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setGravity(Gravity.CENTER);v.setPadding(dp(6),dp(5),dp(6),dp(5));boolean sel=selected.contains(c.id);int r=result(c),stroke=sel?Color.rgb(37,99,235):r==1?Color.rgb(34,197,94):r==-1?Color.rgb(239,68,68):Color.rgb(148,163,184);GradientDrawable gd=new GradientDrawable();gd.setColor(dark?Color.rgb(31,41,55):Color.rgb(224,242,254));gd.setCornerRadius(dp(10));gd.setStroke(dp(sel?3:2),stroke);v.setBackground(gd);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);
TextView no=new TextView(this);no.setText(String.format(Locale.US,"%03d",number));no.setTextSize(10);no.setTextColor(dark?Color.LTGRAY:Color.GRAY);head.addView(no,new LinearLayout.LayoutParams(0,-2,1f));
TextView heart=new TextView(this);heart.setText(favorite(c)?"★":"");heart.setTextSize(18);heart.setGravity(Gravity.RIGHT);heart.setTextColor(Color.rgb(207,159,6));head.addView(heart,new LinearLayout.LayoutParams(dp(28),-2));v.addView(head);TextView p=new TextView(this);p.setText(c.p);p.setTextSize(14);p.setTextColor(dark?Color.WHITE:Color.rgb(20,20,20));p.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);p.setGravity(Gravity.CENTER);p.setMaxLines(3);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,0,1f);v.addView(p,pp);v.setOnClickListener(x->{if(!selected.isEmpty()){toggle(c,v);return;}cardActions(c,number);});v.setOnLongClickListener(x->{toggle(c,v);return true;});return v;}
 void toggle(Card c,View v){if(selected.contains(c.id))selected.remove(c.id);else selected.add(c.id);selectionBar.setVisibility(selected.isEmpty()?View.GONE:View.VISIBLE);selectedCount.setText(selected.size()+" selected");updateSelectAllLabel();styleTile(v,c);}
 void styleTile(View v,Card c){boolean sel=selected.contains(c.id);int r=result(c),stroke=sel?Color.rgb(37,99,235):r==1?Color.rgb(34,197,94):r==-1?Color.rgb(239,68,68):Color.rgb(148,163,184);GradientDrawable gd=new GradientDrawable();gd.setColor(dark?Color.rgb(31,41,55):Color.rgb(224,242,254));gd.setCornerRadius(dp(10));gd.setStroke(dp(sel?3:2),stroke);v.setBackground(gd);}

 ArrayList<Card> visibleCards(){
  ArrayList<Card>a=new ArrayList<>();
  for(Card c:cards)if(c.lang.equals(lang)&&matchesFilter(c)){
   if(query.isEmpty()||c.p.toLowerCase().contains(query)||c.en.toLowerCase().contains(query)||c.fa.toLowerCase().contains(query)||c.n.toLowerCase().contains(query))a.add(c);
  }
  return a;
 }
 void updateSelectAllLabel(){
  if(selectAll==null)return;
  ArrayList<Card>a=visibleCards();boolean all=!a.isEmpty();
  for(Card c:a)if(!selected.contains(c.id)){all=false;break;}
  selectAll.setText(all?"Unselect All":"Select All");
 }
 void toggleSelectAll(){
  ArrayList<Card>a=visibleCards();if(a.isEmpty())return;
  boolean all=true;for(Card c:a)if(!selected.contains(c.id)){all=false;break;}
  if(all){for(Card c:a)selected.remove(c.id);}else{for(Card c:a)selected.add(c.id);}
  selectionBar.setVisibility(selected.isEmpty()?View.GONE:View.VISIBLE);
  selectedCount.setText(selected.size()+" selected");
  updateSelectAllLabel();
  renderGrid();
 }
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 void cardActions(Card c,int number){showCardDialog(c);}
 void showCardDialog(Card c){
  final Dialog dlg=new Dialog(this);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setPadding(0,0,0,0);
  LinearLayout wrap=new LinearLayout(this);wrap.setOrientation(LinearLayout.VERTICAL);wrap.setPadding(dp(18),dp(18),dp(18),dp(16));
  GradientDrawable cardFrame=new GradientDrawable();cardFrame.setColor(dark?Color.rgb(30,30,30):Color.WHITE);cardFrame.setStroke(dp(4),Color.rgb(207,159,6));cardFrame.setCornerRadius(dp(18));wrap.setBackground(cardFrame);scroll.addView(wrap,new ScrollView.LayoutParams(-1,-1));

  TextView phraseTitle=new TextView(this);phraseTitle.setText(c.p);phraseTitle.setTextSize(34);phraseTitle.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);phraseTitle.setGravity(Gravity.CENTER);phraseTitle.setTextColor(dark?Color.WHITE:Color.rgb(17,24,39));LinearLayout.LayoutParams phraseParams=new LinearLayout.LayoutParams(-1,-2);phraseParams.setMargins(0,dp(12),0,dp(4));wrap.addView(phraseTitle,phraseParams);
  ImageButton fav=new ImageButton(this);fav.setBackgroundColor(Color.TRANSPARENT);fav.setContentDescription("Favorite");fav.setImageResource(favorite(c)?android.R.drawable.btn_star_big_on:android.R.drawable.btn_star_big_off);LinearLayout.LayoutParams favP=new LinearLayout.LayoutParams(dp(52),dp(52));favP.gravity=Gravity.CENTER_HORIZONTAL;favP.setMargins(0,0,0,dp(14));wrap.addView(fav,favP);fav.setOnClickListener(v->{boolean nv=!favorite(c);sp.edit().putBoolean(c.id+"_favorite",nv).apply();fav.setImageResource(nv?android.R.drawable.btn_star_big_on:android.R.drawable.btn_star_big_off);renderGrid();});
  ImageButton speak=new ImageButton(this);speak.setImageResource(android.R.drawable.ic_lock_silent_mode_off);speak.setContentDescription("Play phrase");speak.setColorFilter(Color.rgb(17,17,17));GradientDrawable sg=new GradientDrawable();sg.setColor(Color.rgb(134,239,172));sg.setCornerRadius(dp(22));speak.setBackground(sg);LinearLayout.LayoutParams speakP=new LinearLayout.LayoutParams(dp(46),dp(46));speakP.gravity=Gravity.CENTER_HORIZONTAL;speakP.setMargins(0,0,0,dp(16));wrap.addView(speak,speakP);speak.setOnClickListener(v->speakPhrase(c));

  addDetailSection(wrap,"English Meaning",blank(c.en),false);
  addDetailSection(wrap,"معنی فارسی",blank(c.fa),true);
  addDetailSection(wrap,"Example",blank(c.e),false);addDetailSection(wrap,"Tag",blank(c.n),false);

  LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setGravity(Gravity.CENTER);
  Button edit=actionButton("Edit",Color.rgb(124,143,204));Button move=actionButton("Move Box",Color.rgb(133,204,124));Button del=actionButton("Delete",Color.rgb(239,68,68));
  LinearLayout.LayoutParams bp1=new LinearLayout.LayoutParams(0,dp(50),1f);bp1.setMargins(0,0,dp(4),0);LinearLayout.LayoutParams bp2=new LinearLayout.LayoutParams(0,dp(50),1f);bp2.setMargins(dp(2),0,dp(2),0);LinearLayout.LayoutParams bp3=new LinearLayout.LayoutParams(0,dp(50),1f);bp3.setMargins(dp(4),0,0,0);actions.addView(edit,bp1);actions.addView(move,bp2);actions.addView(del,bp3);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,-2);ap.setMargins(0,dp(18),0,dp(10));wrap.addView(actions,ap);

  Button close=new Button(this);close.setText("Close");close.setAllCaps(false);close.setTextSize(16);close.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);close.setTextColor(dark?Color.BLACK:Color.WHITE);GradientDrawable cbg=new GradientDrawable();cbg.setColor(dark?Color.WHITE:Color.BLACK);cbg.setCornerRadius(dp(12));close.setBackground(cbg);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(54));cp.setMargins(0,dp(6),0,0);wrap.addView(close,cp);

  dlg.setContentView(scroll);Window win=dlg.getWindow();if(win!=null){win.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));win.setLayout((int)(getResources().getDisplayMetrics().widthPixels-dp(60)),WindowManager.LayoutParams.WRAP_CONTENT);}
  close.setOnClickListener(v->dlg.dismiss());edit.setOnClickListener(v->{dlg.dismiss();editDialog(c);});move.setOnClickListener(v->{dlg.dismiss();chooseBox(c);});del.setOnClickListener(v->{dlg.dismiss();deleteOne(c);});
  dlg.setOnShowListener(v->{Window w=dlg.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setLayout((int)(getResources().getDisplayMetrics().widthPixels-dp(60)),WindowManager.LayoutParams.WRAP_CONTENT);}});dlg.show();
 }
 void initTts(){tts=new TextToSpeech(this,status->{ttsReady=status==TextToSpeech.SUCCESS;});}
 Locale localeForLanguage(String l){String x=l==null?"":l.toLowerCase(Locale.ROOT);if(x.contains("norwegian")||x.contains("norsk"))return new Locale("nb","NO");if(x.contains("german"))return Locale.GERMAN;if(x.contains("french"))return Locale.FRENCH;if(x.contains("spanish"))return new Locale("es","ES");if(x.contains("italian"))return Locale.ITALIAN;if(x.contains("persian")||x.contains("farsi")||x.contains("فارسی"))return new Locale("fa","IR");return Locale.ENGLISH;}
 void speakPhrase(Card c){if(!ttsReady||tts==null){Toast.makeText(this,"Speech engine is not ready yet.",Toast.LENGTH_SHORT).show();return;}int r=tts.setLanguage(localeForLanguage(c.lang));if(r==TextToSpeech.LANG_MISSING_DATA||r==TextToSpeech.LANG_NOT_SUPPORTED){Toast.makeText(this,"Speech for "+c.lang+" is not installed.",Toast.LENGTH_LONG).show();return;}applyVoiceSettings(c.lang);tts.speak(c.p,TextToSpeech.QUEUE_FLUSH,null,"phrase_"+c.id);}

 void applyVoiceSettings(String language){if(tts==null)return;float rate=sp.getFloat("voice_rate",1.0f);tts.setSpeechRate(rate);try{ArrayList<Voice> vs=voicesFor(language);int idx=Math.max(0,Math.min(3,sp.getInt("voice_type",0)));if(!vs.isEmpty())tts.setVoice(vs.get(Math.min(idx,vs.size()-1)));}catch(Exception ignored){}}
 ArrayList<Voice> voicesFor(String language){ArrayList<Voice> out=new ArrayList<>();if(tts==null||tts.getVoices()==null)return out;Locale target=localeForLanguage(language);for(Voice v:tts.getVoices()){Locale l=v.getLocale();if(l!=null&&l.getLanguage().equals(target.getLanguage())&&!v.isNetworkConnectionRequired())out.add(v);}if(out.size()<4)for(Voice v:tts.getVoices()){Locale l=v.getLocale();if(l!=null&&l.getLanguage().equals(target.getLanguage())&&!out.contains(v))out.add(v);}Collections.sort(out,(a,b)->a.getName().compareToIgnoreCase(b.getName()));return out;}
 void voiceSettings(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(24),dp(8),dp(24),dp(4));TextView speedLabel=new TextView(this);speedLabel.setText("Speech speed");speedLabel.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);box.addView(speedLabel);RadioGroup speeds=new RadioGroup(this);String[] sr={"0.5x","0.75x","1x"};float current=sp.getFloat("voice_rate",1f);for(int i=0;i<3;i++){RadioButton rb=new RadioButton(this);rb.setText(sr[i]);rb.setId(500+i);speeds.addView(rb);if((i==0&&current<.63f)||(i==1&&current>=.63f&&current<.9f)||(i==2&&current>=.9f))rb.setChecked(true);}box.addView(speeds);TextView voiceLabel=new TextView(this);voiceLabel.setText("Speaker voice");voiceLabel.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);voiceLabel.setPadding(0,dp(10),0,0);box.addView(voiceLabel);RadioGroup voices=new RadioGroup(this);ArrayList<Voice> av=voicesFor(lang);for(int i=0;i<4;i++){RadioButton rb=new RadioButton(this);rb.setId(600+i);rb.setText(i<av.size()?"Voice "+(i+1):"Voice "+(i+1)+" (not available)");rb.setEnabled(i<av.size());voices.addView(rb);if(i==sp.getInt("voice_type",0)&&i<av.size())rb.setChecked(true);}box.addView(voices);AlertDialog d=new AlertDialog.Builder(this).setTitle("Voice setting — "+lang).setView(box).setNegativeButton("Close",null).setPositiveButton("Save",null).create();d.setOnShowListener(v->{styleClose(d);d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{int si=speeds.getCheckedRadioButtonId()-500;float rate=si==0?.5f:si==1?.75f:1f;int vi=voices.getCheckedRadioButtonId()-600;if(vi<0)vi=0;sp.edit().putFloat("voice_rate",rate).putInt("voice_type",vi).apply();applyVoiceSettings(lang);d.dismiss();});});d.show();}
 void styleMainButton(Button b){b.setBackgroundTintList(null);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(214,196,77));g.setCornerRadius(dp(28));b.setBackground(g);b.setTextColor(Color.rgb(20,20,20));b.setAllCaps(false);}
 void showStyled(AlertDialog d){
  d.setOnShowListener(v->styleClose(d));
  d.show();
}
 void styleClose(AlertDialog d){
  if(d.getWindow()!=null){GradientDrawable frame=new GradientDrawable();frame.setColor(dark?Color.rgb(30,30,30):Color.WHITE);frame.setStroke(dp(4),Color.rgb(207,159,6));frame.setCornerRadius(dp(18));d.getWindow().setBackgroundDrawable(frame);}
  int bg=dark?Color.WHITE:Color.BLACK, fg=dark?Color.BLACK:Color.WHITE;
  styleDialogButton(d,AlertDialog.BUTTON_NEGATIVE,bg,fg);
  styleDialogButton(d,AlertDialog.BUTTON_POSITIVE,bg,fg);
  styleDialogButton(d,AlertDialog.BUTTON_NEUTRAL,bg,fg);
}
 void styleDialogButton(AlertDialog d,int which,int bg,int fg){Button b=d.getButton(which);if(b!=null){b.setBackgroundTintList(null);b.setTextColor(fg);b.setAllCaps(false);GradientDrawable g=new GradientDrawable();g.setColor(bg);g.setCornerRadius(dp(12));b.setBackground(g);b.setPadding(dp(18),0,dp(18),0);LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)b.getLayoutParams();p.setMargins(dp(5),dp(3),dp(5),dp(3));b.setLayoutParams(p);}}

 void handleNotificationIntent(Intent i){if(i==null)return;String id=i.getStringExtra("open_card_id");if(id==null)return;for(Card c:cards)if(c.id.equals(id)){lang=c.lang;sp.edit().putString("active_language",lang).apply();loadFilter();renderLibrary();new Handler(Looper.getMainLooper()).postDelayed(()->showCardDialog(c),180);break;}}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handleNotificationIntent(i);}
 void notificationSettings(){
  LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(24),dp(10),dp(24),dp(4));
  TextView timeLabel=new TextView(this);timeLabel.setText("First notification time");timeLabel.setTextSize(16);box.addView(timeLabel);
  Button time=new Button(this);int hour=sp.getInt("notif_hour",18),minute=sp.getInt("notif_minute",0);time.setText(String.format(Locale.US,"%02d:%02d",hour,minute));box.addView(time,new LinearLayout.LayoutParams(-1,dp(52)));
  TextView countLabel=new TextView(this);countLabel.setText("Notifications per day");countLabel.setTextSize(16);LinearLayout.LayoutParams clp=new LinearLayout.LayoutParams(-1,-2);clp.setMargins(0,dp(18),0,dp(6));box.addView(countLabel,clp);
  Spinner count=new Spinner(this);String[] counts={"1","2","3","4","5"};ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,counts);count.setAdapter(ad);count.setSelection(Math.max(0,Math.min(4,sp.getInt("notif_count",1)-1)));box.addView(count,new LinearLayout.LayoutParams(-1,dp(52)));
  final int[] chosen={hour,minute};time.setOnClickListener(v->new TimePickerDialog(this,(view,h,m)->{chosen[0]=h;chosen[1]=m;time.setText(String.format(Locale.US,"%02d:%02d",h,m));},chosen[0],chosen[1],true).show());
  AlertDialog d=new AlertDialog.Builder(this).setTitle("Notification").setView(box).setNegativeButton("Close",null).setPositiveButton("Save",(x,w)->{sp.edit().putInt("notif_hour",chosen[0]).putInt("notif_minute",chosen[1]).putInt("notif_count",count.getSelectedItemPosition()+1).putBoolean("notif_enabled",true).apply();NotificationScheduler.schedule(this);requestNotificationPermission();Toast.makeText(this,"Hard-card notifications scheduled",Toast.LENGTH_SHORT).show();}).create();showStyled(d);
 }
 void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},900);}

 @Override public void onBackPressed(){if(drawerOverlay!=null&&drawerOverlay.getVisibility()==View.VISIBLE){closeMenu();return;}if(dailyMode||practiceView.getVisibility()==View.VISIBLE){leavePractice();return;}super.onBackPressed();}
 @Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
 Button actionButton(String text,int color){
  Button b=new Button(this);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);b.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);
  GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(14));b.setBackground(g);b.setPadding(dp(6),0,dp(6),0);return b;
 }
 void addDetailSection(LinearLayout parent,String titleText,String value,boolean rtl){
  if(value==null||value.trim().isEmpty()||value.trim().equals("—"))return;
  TextView t=new TextView(this);t.setText(titleText);t.setTextSize(14);t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);t.setTextColor(dark?Color.rgb(147,197,253):Color.rgb(30,64,175));
  LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.setMargins(0,dp(5),0,dp(3));parent.addView(t,tp);
  TextView v=new TextView(this);v.setText(value);v.setTextSize(rtl?18:17);v.setTextColor(dark?Color.WHITE:Color.rgb(31,41,55));if(rtl){v.setGravity(Gravity.RIGHT);v.setTextDirection(View.TEXT_DIRECTION_RTL);}
  LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,-2);vp.setMargins(0,0,0,dp(10));parent.addView(v,vp);
 }
 String blank(String s){return s==null||s.trim().isEmpty()?"—":s;}
 LinearLayout form(Card c){
  LinearLayout l=new LinearLayout(this);l.setPadding(dp(16),dp(14),dp(16),dp(14));l.setOrientation(LinearLayout.VERTICAL);GradientDrawable formFrame=new GradientDrawable();formFrame.setColor(dark?Color.rgb(30,30,30):Color.WHITE);formFrame.setStroke(dp(4),Color.rgb(207,159,6));formFrame.setCornerRadius(dp(18));l.setBackground(formFrame);
  String[]h={"Phrase","English Meaning","معنی فارسی","Example","Tag"};String[]v=c==null?new String[]{"","","","",""}:new String[]{c.p,c.en,c.fa,c.e,c.n};
  for(int i=0;i<h.length;i++){TextView label=new TextView(this);label.setText(h[i]);label.setTextSize(14);label.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);label.setTextColor(dark?Color.WHITE:Color.rgb(17,24,39));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,i==0?dp(2):dp(12),0,dp(4));l.addView(label,lp);EditText x=new EditText(this);x.setHint("Enter "+h[i].toLowerCase());x.setText(v[i]);x.setTextSize(16);x.setPadding(dp(12),dp(10),dp(12),dp(10));x.setMinHeight(dp(i==3?68:56));x.setSingleLine(i!=3);if(i==2){x.setGravity(Gravity.RIGHT);x.setTextDirection(View.TEXT_DIRECTION_RTL);}l.addView(x,new LinearLayout.LayoutParams(-1,-2));}
  return l;
 }
 void editDialog(Card c){LinearLayout l=form(c);AlertDialog d=new AlertDialog.Builder(this).setTitle(c==null?"Add card to "+lang:"Edit card").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(z,w)->{String p=((EditText)l.getChildAt(1)).getText().toString().trim();if(p.isEmpty())return;String en=((EditText)l.getChildAt(3)).getText().toString(),fa=((EditText)l.getChildAt(5)).getText().toString(),e=((EditText)l.getChildAt(7)).getText().toString(),tag=((EditText)l.getChildAt(9)).getText().toString();if(c==null)cards.add(new Card("c"+System.currentTimeMillis(),lang,p,en,fa,tag,e));else{c.p=p;c.en=en;c.fa=fa;c.n=tag;c.e=e;}saveCustom();renderLibrary();}).create();showStyled(d);}
 void deleteOne(Card c){AlertDialog d=new AlertDialog.Builder(this).setTitle("Delete card?").setMessage(c.p).setNegativeButton("Cancel",null).setPositiveButton("Delete",(q,w)->{cards.remove(c);sp.edit().putBoolean(c.id+"_deleted",true).apply();saveCustom();renderLibrary();}).create();showStyled(d);}
 void deleteSelected(){if(selected.isEmpty())return;AlertDialog d=new AlertDialog.Builder(this).setTitle("Delete "+selected.size()+" cards?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(dialog,w)->{ArrayList<Card>gone=new ArrayList<>();for(Card c:cards)if(selected.contains(c.id)){gone.add(c);sp.edit().putBoolean(c.id+"_deleted",true).apply();}cards.removeAll(gone);selected.clear();saveCustom();renderLibrary();}).create();showStyled(d);}
 void chooseBox(Card c){String[]b={"Box 1","Box 2","Box 3","Box 4","Box 5"};AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Move "+c.p).setSingleChoiceItems(b,box(c)-1,(d,w)->{sp.edit().putInt(c.id+"_box",w+1).apply();d.dismiss();renderLibrary();}).create();showStyled(dlg);}
 void moveSelected(){if(selected.isEmpty())return;String[]b={"Box 1","Box 2","Box 3","Box 4","Box 5"};AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Move selected cards").setItems(b,(d,w)->{SharedPreferences.Editor ed=sp.edit();for(Card c:cards)if(selected.contains(c.id))ed.putInt(c.id+"_box",w+1);ed.apply();selected.clear();renderLibrary();}).create();showStyled(dlg);}
 void updateStats(){int total=0,g=0,h=0;for(Card c:cards)if(c.lang.equals(lang)){total++;if(result(c)==1)g++;else if(result(c)==-1)h++;}int u=Math.max(0,total-g-h);weight(goodBar,g);weight(hardBar,h);weight(unseenBar,u);goodStats.setText("Good "+g);hardStats.setText("Hard "+h);stats.setText("Unreviewed "+u);}
 void weight(View v,int w){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.weight=Math.max(0,w);p.width=0;v.setLayoutParams(p);}
 void showMenu(){drawerOverlay.setVisibility(View.VISIBLE);drawerPanel.setTranslationX(-dp(300));drawerPanel.animate().translationX(0).setDuration(220).setInterpolator(new DecelerateInterpolator()).start();}
 void closeMenu(){if(drawerOverlay.getVisibility()!=View.VISIBLE)return;drawerPanel.animate().translationX(-dp(300)).setDuration(180).withEndAction(()->drawerOverlay.setVisibility(View.GONE)).start();}
 void loadFilter(){filterFavorites=sp.getBoolean("filter_fav_"+lang,false);filterTag=sp.getString("filter_tag_"+lang,"");}
 void saveFilter(){sp.edit().putBoolean("filter_fav_"+lang,filterFavorites).putString("filter_tag_"+lang,filterTag).apply();}
 void updateFilterVisual(){boolean active=filterFavorites||(filterTag!=null&&!filterTag.isEmpty());filterButton.setImageResource(R.drawable.ic_filter_funnel);GradientDrawable gd=new GradientDrawable();gd.setCornerRadius(dp(10));gd.setColor(active?Color.rgb(214,196,77):Color.TRANSPARENT);filterButton.setBackground(gd);filterButton.setColorFilter(dark?Color.WHITE:Color.rgb(31,41,55));}
 ArrayList<String> tagsForLanguage(){TreeSet<String> set=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);for(Card c:cards)if(c.lang.equals(lang)&&c.n!=null&&!c.n.trim().isEmpty())set.add(c.n.trim());return new ArrayList<>(set);}
 void showFilterDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(24),dp(8),dp(24),dp(8));CheckBox fav=new CheckBox(this);fav.setText("Favorites only");fav.setChecked(filterFavorites);box.addView(fav);TextView lab=new TextView(this);lab.setText("Tag");lab.setPadding(0,dp(12),0,dp(4));box.addView(lab);Spinner tags=new Spinner(this);ArrayList<String> opts=new ArrayList<>();opts.add("All tags");opts.addAll(tagsForLanguage());tags.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,opts));int pos=0;if(!filterTag.isEmpty()){int z=opts.indexOf(filterTag);if(z>=0)pos=z;}tags.setSelection(pos);box.addView(tags);AlertDialog d=new AlertDialog.Builder(this).setTitle("Filter — "+lang).setView(box).setNegativeButton("Clear",null).setPositiveButton("Apply",null).create();d.setOnShowListener(v->{styleClose(d);d.getButton(AlertDialog.BUTTON_NEGATIVE).setOnClickListener(q->{filterFavorites=false;filterTag="";saveFilter();d.dismiss();renderLibrary();});d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(q->{filterFavorites=fav.isChecked();filterTag=tags.getSelectedItemPosition()==0?"":String.valueOf(tags.getSelectedItem());saveFilter();d.dismiss();renderLibrary();});});d.show();}
 void chooseMode(){String[]m={"Dark","Light","System default"};String curMode=sp.getString("theme","system");int checked=curMode.equals("dark")?0:curMode.equals("light")?1:2;AlertDialog d=new AlertDialog.Builder(this).setTitle("Mode").setSingleChoiceItems(m,checked,(x,w)->{setTheme(w==0?"dark":w==1?"light":"system");x.dismiss();}).setNegativeButton("Close",null).create();showStyled(d);}
  void chooseLanguage(){String[]a=decks.toArray(new String[0]);AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Switch language").setSingleChoiceItems(a,decks.indexOf(lang),(d,w)->{lang=decks.get(w);sp.edit().putString("active_language",lang).apply();loadFilter();selected.clear();search.setText("");d.dismiss();renderLibrary();}).setNegativeButton("Close",null).create();showStyled(dlg);}
 void addLanguage(){EditText i=new EditText(this);i.setHint("e.g. German");AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Add new language").setView(i).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{String n=i.getText().toString().trim();if(!n.isEmpty()&&!decks.contains(n)){decks.add(n);saveDecks();lang=n;sp.edit().putString("active_language",lang).apply();renderLibrary();}}).create();showStyled(dlg);}
 void setTheme(String t){String old=sp.getString("theme","system");if(old.equals(t))return;sp.edit().putString("theme",t).apply();applyTheme();}
 String appVersion(){try{return getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Exception e){return "";}}
 void showAbout(){AlertDialog d=new AlertDialog.Builder(this).setTitle("About Zope Flash Cards").setMessage("This is an experimental Android Flash card application for personal use. Created by Omid.R.B . Version "+appVersion()).setPositiveButton("OK",null).create();showStyled(d);}
 void viewByBox(){String[]b=new String[5];for(int k=1;k<=5;k++){int n=0;for(Card c:cards)if(c.lang.equals(lang)&&box(c)==k)n++;b[k-1]="Box "+k+"  ("+n+" cards)";}AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Leitner Boxes — "+lang).setItems(b,(d,w)->{query="";search.setText("");renderLibrary();for(int i=0;i<cardGrid.getChildCount();i++){View v=cardGrid.getChildAt(i);v.setVisibility(View.VISIBLE);}Toast.makeText(this,"Box "+(w+1)+": tap cards to edit their box",Toast.LENGTH_LONG).show();}).create();showStyled(dlg);}
 void resetLeitner(){AlertDialog d=new AlertDialog.Builder(this).setTitle("Reset Leitner progress?").setMessage("This resets all "+lang+" cards to Box 1 and clears Good/Hard status.").setNegativeButton("Cancel",null).setPositiveButton("Reset",(dialog,w)->{SharedPreferences.Editor ed=sp.edit();for(Card c:cards)if(c.lang.equals(lang)){ed.remove(c.id+"_box");ed.remove(c.id+"_due");ed.remove(c.id+"_result");}ed.apply();renderLibrary();}).create();showStyled(d);}
 void startDaily(){dailyCards.clear();dailyGood=0;dailyHard=0;dailyIndex=0;long y=dayKey()-1;ArrayList<Card>h=new ArrayList<>(),o=new ArrayList<>();for(Card c:cards)if(c.lang.equals(lang)&&matchesFilter(c)){if(sp.getLong(c.id+"_dailyHard",-99)==y)h.add(c);else o.add(c);}Collections.shuffle(o);dailyCards.addAll(h);for(Card c:o)if(dailyCards.size()<10)dailyCards.add(c);while(dailyCards.size()>10)dailyCards.remove(dailyCards.size()-1);if(dailyCards.isEmpty()){Toast.makeText(this,"No cards in "+lang,Toast.LENGTH_SHORT).show();return;}dailyMode=true;libraryView.setVisibility(View.GONE);practiceView.setVisibility(View.VISIBLE);showDaily();}
 long dayKey(){Calendar c=Calendar.getInstance();return c.get(Calendar.YEAR)*1000L+c.get(Calendar.DAY_OF_YEAR);}
 void showDaily(){if(dailyIndex>=dailyCards.size()){dailyMode=false;AlertDialog done=new AlertDialog.Builder(this).setTitle("Daily Practice Complete").setMessage("Reviewed: "+dailyCards.size()+"\n\nGood: "+dailyGood+"\nHard: "+dailyHard+"\n\nHard cards are prioritized tomorrow.").setPositiveButton("Back to Library",(d,w)->renderLibrary()).create();showStyled(done);return;}cur=dailyCards.get(dailyIndex);practiceProgress.setText("Daily Practice  "+(dailyIndex+1)+" / "+dailyCards.size());phrase.setText(cur.p);enMeaning.setText(blank(cur.en));faMeaning.setText(blank(cur.fa));example.setText(blank(cur.e));answerBox.setVisibility(View.GONE);rating.setVisibility(View.GONE);show.setVisibility(View.VISIBLE);studyArea.setAlpha(0f);studyArea.setTranslationX(dp(40));studyArea.animate().alpha(1f).translationX(0).setDuration(180).setInterpolator(new DecelerateInterpolator()).start();studyArea.postDelayed(()->{if(dailyMode&&cur!=null)speakPhrase(cur);},220);}
 void rate(boolean ok){if(cur==null)return;int b=ok?Math.min(5,box(cur)+1):1;sp.edit().putInt(cur.id+"_box",b).putLong(cur.id+"_due",System.currentTimeMillis()+interval(b)).putInt(cur.id+"_result",ok?1:-1).apply();if(ok)dailyGood++;else{dailyHard++;sp.edit().putLong(cur.id+"_dailyHard",dayKey()).apply();}dailyIndex++;showDaily();}
 void leavePractice(){AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Leave Daily Practice?").setMessage("Your ratings so far are saved.").setNegativeButton("Stay",null).setPositiveButton("Leave",(d,w)->renderLibrary()).create();showStyled(dlg);}
 void exportCsv(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"phrase_cards_"+lang.toLowerCase()+".csv");startActivityForResult(i,EXPORT_CSV);}
 void importCsv(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("text/*");startActivityForResult(i,IMPORT_CSV);}
 String esc(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK||data==null)return;try{Uri u=data.getData();if(r==EXPORT_CSV){BufferedWriter w=new BufferedWriter(new OutputStreamWriter(getContentResolver().openOutputStream(u),"UTF-8"));w.write("Phrase,English Meaning,Persian Meaning,Example\n");int count=0;for(Card x:cards)if(x.lang.equals(lang)){w.write(esc(x.p)+","+esc(x.en)+","+esc(x.fa)+","+esc(x.e)+"\n");count++;}w.close();Toast.makeText(this,count+" "+lang+" cards exported",Toast.LENGTH_LONG).show();}else{BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u),"UTF-8"));ArrayList<ArrayList<String>> rows=new ArrayList<>();String line;while((line=br.readLine())!=null)if(!line.trim().isEmpty())rows.add(parseCsv(line));br.close();if(rows.isEmpty())return;int phraseCol=0,enCol=-1,faCol=-1,exCol=-1,startRow=0;ArrayList<String> hdr=rows.get(0);boolean header=false;for(int i=0;i<hdr.size();i++){String h=hdr.get(i).trim().toLowerCase(Locale.ROOT).replace("_"," ");if(h.contains("phrase")||h.equals("word")||h.contains("expression")){phraseCol=i;header=true;}else if((h.contains("persian")||h.contains("farsi")||h.contains("فارسی"))){faCol=i;header=true;}else if(h.contains("example")||h.contains("sentence")){exCol=i;header=true;}else if(h.contains("english")||h.contains("meaning")||h.contains("definition")||h.contains("explanation")){enCol=i;header=true;}}if(header)startRow=1;int count=0;for(int ri=startRow;ri<rows.size();ri++){ArrayList<String>a=rows.get(ri);if(a.isEmpty())continue;String p=getCol(a,phraseCol),enV=getCol(a,enCol),faV=getCol(a,faCol),exV=getCol(a,exCol);if(!header){p=getCol(a,0);for(int i=1;i<a.size();i++){String v=getCol(a,i);if(v.isEmpty())continue;if(hasPersian(v)&&faV.isEmpty())faV=v;else if(looksExample(v)&&exV.isEmpty())exV=v;else if(enV.isEmpty())enV=v;else if(exV.isEmpty())exV=v;}}else{for(int i=0;i<a.size();i++){if(i==phraseCol||i==enCol||i==faCol||i==exCol)continue;String v=getCol(a,i);if(v.isEmpty())continue;if(hasPersian(v)&&faV.isEmpty())faV=v;else if(looksExample(v)&&exV.isEmpty())exV=v;else if(enV.isEmpty())enV=v;}}if(!p.trim().isEmpty()){cards.add(new Card("c"+System.currentTimeMillis()+"_"+count,lang,p.trim(),enV.trim(),faV.trim(),"",exV.trim()));count++;}}saveCustom();Toast.makeText(this,count+" cards intelligently imported into "+lang,Toast.LENGTH_LONG).show();renderLibrary();}}catch(Exception e){AlertDialog er=new AlertDialog.Builder(this).setTitle("CSV error").setMessage(String.valueOf(e.getMessage())).setPositiveButton("OK",null).create();showStyled(er);}}
 String getCol(ArrayList<String>a,int i){return i>=0&&i<a.size()?a.get(i):"";}
 boolean looksExample(String s){String x=s.trim();return x.length()>18&&(x.endsWith(".")||x.endsWith("!")||x.endsWith("?")||x.toLowerCase(Locale.ROOT).startsWith("for example"));}
 ArrayList<String>parseCsv(String s){ArrayList<String>a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='"'){b.append('"');i++;}else q=!q;}else if(c==','&&!q){a.add(b.toString());b.setLength(0);}else b.append(c);}a.add(b.toString());return a;}
 @Override public boolean dispatchTouchEvent(android.view.MotionEvent e){if(e.getAction()==android.view.MotionEvent.ACTION_UP){View hit=findButtonAt(getWindow().getDecorView(),e.getRawX(),e.getRawY());if(hit instanceof Button||hit instanceof ImageButton)vibrateClick();}return super.dispatchTouchEvent(e);}
 View findButtonAt(View v,float x,float y){if(v.getVisibility()!=View.VISIBLE)return null;int[]loc=new int[2];v.getLocationOnScreen(loc);if(x<loc[0]||x>loc[0]+v.getWidth()||y<loc[1]||y>loc[1]+v.getHeight())return null;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=g.getChildCount()-1;i>=0;i--){View h=findButtonAt(g.getChildAt(i),x,y);if(h!=null)return h;}}return (v instanceof Button||v instanceof ImageButton)?v:null;}
 void vibrateClick(){try{Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v==null)return;if(Build.VERSION.SDK_INT>=26)v.vibrate(VibrationEffect.createOneShot(18,VibrationEffect.DEFAULT_AMPLITUDE));else v.vibrate(18);}catch(Exception ignored){}}

}
