package com.phrasecards.app;
import android.app.*;import android.os.*;import android.content.*;import android.content.res.Configuration;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.text.*;import android.view.*;import android.view.animation.*;import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;import androidx.appcompat.app.AppCompatDelegate;import org.json.*;import java.util.*;import java.io.*;

public class MainActivity extends AppCompatActivity{
 static class Card{String id,lang,p,en,fa,n,e;Card(String a,String b,String c,String d,String f,String g,String h){id=a;lang=b;p=c;en=d;fa=f;n=g;e=h;}}
 ArrayList<Card>cards=new ArrayList<>(),dailyCards=new ArrayList<>();ArrayList<String>decks=new ArrayList<>();HashSet<String>selected=new HashSet<>();
 SharedPreferences sp;Card cur;String lang="English",query="";int dailyIndex=0,dailyGood=0,dailyHard=0;boolean dailyMode=false,dark=false;
 LinearLayout libraryView,practiceView,answerBox,rating,studyArea,selectionBar;GridLayout cardGrid;
 TextView title,currentLanguage,cardCount,stats,selectedCount,practiceProgress,phrase,enMeaning,faMeaning,note,example;
 EditText search;View goodBar,hardBar,unseenBar;Button menuButton,daily,add,show,hard,good,backLibrary,deleteSelected,moveSelected,cancelSelection;
 static final int EXPORT_CSV=401,IMPORT_CSV=402;

 public void onCreate(Bundle b){sp=getSharedPreferences("phrasecards_v7",MODE_PRIVATE);applyTheme();super.onCreate(b);setContentView(R.layout.activity_main);bind();loadSeed();loadCustom();loadDecks();dark=isDark();styleTheme();wire();renderLibrary();}
 void applyTheme(){String t=sp.getString("theme","light");AppCompatDelegate.setDefaultNightMode(t.equals("dark")?AppCompatDelegate.MODE_NIGHT_YES:AppCompatDelegate.MODE_NIGHT_NO);}
 boolean isDark(){return (getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES;}
 void bind(){libraryView=findViewById(R.id.libraryView);practiceView=findViewById(R.id.practiceView);answerBox=findViewById(R.id.answerBox);rating=findViewById(R.id.rating);studyArea=findViewById(R.id.studyArea);selectionBar=findViewById(R.id.selectionBar);cardGrid=findViewById(R.id.cardGrid);title=findViewById(R.id.title);currentLanguage=findViewById(R.id.currentLanguage);cardCount=findViewById(R.id.cardCount);stats=findViewById(R.id.stats);selectedCount=findViewById(R.id.selectedCount);practiceProgress=findViewById(R.id.practiceProgress);phrase=findViewById(R.id.phrase);enMeaning=findViewById(R.id.meaningEnglish);faMeaning=findViewById(R.id.meaningPersian);note=findViewById(R.id.note);example=findViewById(R.id.example);search=findViewById(R.id.search);goodBar=findViewById(R.id.goodProgress);hardBar=findViewById(R.id.hardProgress);unseenBar=findViewById(R.id.unseenProgress);menuButton=findViewById(R.id.menuButton);daily=findViewById(R.id.daily);add=findViewById(R.id.add);show=findViewById(R.id.show);hard=findViewById(R.id.hard);good=findViewById(R.id.good);backLibrary=findViewById(R.id.backLibrary);deleteSelected=findViewById(R.id.deleteSelected);moveSelected=findViewById(R.id.moveSelected);cancelSelection=findViewById(R.id.cancelSelection);}
 void wire(){menuButton.setOnClickListener(v->showMenu());daily.setOnClickListener(v->startDaily());add.setOnClickListener(v->editDialog(null));show.setOnClickListener(v->{answerBox.setVisibility(View.VISIBLE);show.setVisibility(View.GONE);rating.setVisibility(View.VISIBLE);});hard.setOnClickListener(v->rate(false));good.setOnClickListener(v->rate(true));backLibrary.setOnClickListener(v->leavePractice());deleteSelected.setOnClickListener(v->deleteSelected());moveSelected.setOnClickListener(v->moveSelected());cancelSelection.setOnClickListener(v->{selected.clear();renderLibrary();});search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){query=s.toString().trim().toLowerCase();renderGrid();}public void afterTextChanged(Editable e){}});}
 void styleTheme(){dark=isDark();int bg=dark?Color.rgb(18,18,18):Color.rgb(250,250,250),fg=dark?Color.rgb(240,240,240):Color.rgb(25,25,25),panel=dark?Color.rgb(30,30,30):Color.WHITE;findViewById(R.id.root).setBackgroundColor(bg);libraryView.setBackgroundColor(bg);practiceView.setBackgroundColor(bg);studyArea.setBackgroundColor(panel);title.setTextColor(fg);currentLanguage.setTextColor(fg);cardCount.setTextColor(fg);stats.setTextColor(dark?Color.LTGRAY:Color.DKGRAY);phrase.setTextColor(fg);enMeaning.setTextColor(fg);faMeaning.setTextColor(fg);note.setTextColor(fg);example.setTextColor(fg);practiceProgress.setTextColor(fg);selectedCount.setTextColor(fg);}
 boolean hasPersian(String s){for(char c:s.toCharArray())if(c>=0x0600&&c<=0x06FF)return true;return false;}
 void loadSeed(){try{InputStream in=getAssets().open("seed_cards.json");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();JSONArray a=new JSONArray(out.toString("UTF-8"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);String id=o.getString("id");if(sp.getBoolean(id+"_deleted",false))continue;String raw=o.optString("tr"),en="",fa="";if(hasPersian(raw))fa=raw;else en=raw;cards.add(new Card(id,o.getString("lang"),o.getString("phrase"),en,fa,o.optString("note"),o.optString("ex")));}}catch(Exception e){e.printStackTrace();}}
 void loadCustom(){try{JSONArray a=new JSONArray(sp.getString("customCards","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);cards.add(new Card(o.getString("id"),o.getString("lang"),o.getString("p"),o.optString("en"),o.optString("fa"),o.optString("n"),o.optString("e")));}}catch(Exception ignored){}}
 void saveCustom(){JSONArray a=new JSONArray();try{for(Card c:cards)if(c.id.startsWith("c")){JSONObject o=new JSONObject();o.put("id",c.id);o.put("lang",c.lang);o.put("p",c.p);o.put("en",c.en);o.put("fa",c.fa);o.put("n",c.n);o.put("e",c.e);a.put(o);}}catch(Exception ignored){}sp.edit().putString("customCards",a.toString()).apply();}
 void loadDecks(){decks.add("English");decks.add("Norwegian");try{JSONArray a=new JSONArray(sp.getString("decks","[]"));for(int i=0;i<a.length();i++){String d=a.getString(i);if(!decks.contains(d))decks.add(d);}}catch(Exception ignored){}}
 void saveDecks(){JSONArray a=new JSONArray();for(String d:decks)if(!d.equals("English")&&!d.equals("Norwegian"))a.put(d);sp.edit().putString("decks",a.toString()).apply();}
 int box(Card c){return sp.getInt(c.id+"_box",1);}int result(Card c){return sp.getInt(c.id+"_result",0);}long interval(int b){long d=86400000L;return b<=1?0:b==2?d:b==3?3*d:b==4?7*d:14*d;}
 ArrayList<Card>active(){ArrayList<Card>a=new ArrayList<>();for(Card c:cards)if(c.lang.equals(lang))a.add(c);return a;}
 void renderLibrary(){libraryView.setVisibility(View.VISIBLE);practiceView.setVisibility(View.GONE);dailyMode=false;currentLanguage.setText(lang);ArrayList<Card>a=active();cardCount.setText(a.size()+" cards");updateStats();selectionBar.setVisibility(selected.isEmpty()?View.GONE:View.VISIBLE);selectedCount.setText(selected.size()+" selected");renderGrid();}
 void renderGrid(){cardGrid.removeAllViews();ArrayList<Card>a=active();int shown=0;for(int i=0;i<a.size();i++){Card c=a.get(i);if(!query.isEmpty()&&!c.p.toLowerCase().contains(query)&&!c.en.toLowerCase().contains(query)&&!c.fa.toLowerCase().contains(query))continue;shown++;cardGrid.addView(tile(c,i+1),tileParams());}if(shown==0){TextView empty=new TextView(this);empty.setText(query.isEmpty()?"No cards yet":"No matching cards");empty.setGravity(Gravity.CENTER);empty.setPadding(10,40,10,40);empty.setTextColor(dark?Color.LTGRAY:Color.DKGRAY);GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.columnSpec=GridLayout.spec(0,3,1f);p.width=0;p.height=GridLayout.LayoutParams.WRAP_CONTENT;cardGrid.addView(empty,p);}}
 GridLayout.LayoutParams tileParams(){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(116);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(3),dp(3),dp(3),dp(3));return p;}
 View tile(Card c,int number){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setGravity(Gravity.CENTER);v.setPadding(dp(6),dp(5),dp(6),dp(5));boolean sel=selected.contains(c.id);int r=result(c),stroke=sel?Color.rgb(37,99,235):r==1?Color.rgb(34,197,94):r==-1?Color.rgb(239,68,68):Color.rgb(148,163,184);GradientDrawable gd=new GradientDrawable();gd.setColor(dark?Color.rgb(34,34,34):Color.WHITE);gd.setCornerRadius(dp(10));gd.setStroke(dp(sel?3:2),stroke);v.setBackground(gd);TextView no=new TextView(this);no.setText(String.format(Locale.US,"%03d",number));no.setTextSize(10);no.setTextColor(dark?Color.LTGRAY:Color.GRAY);v.addView(no);TextView p=new TextView(this);p.setText(c.p);p.setTextSize(14);p.setTextColor(dark?Color.WHITE:Color.rgb(20,20,20));p.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);p.setGravity(Gravity.CENTER);p.setMaxLines(3);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,0,1f);v.addView(p,pp);TextView b=new TextView(this);b.setText("Box "+box(c)+(r==1?"  ✓":r==-1?"  !":""));b.setTextSize(10);b.setTextColor(stroke);v.addView(b);v.setOnClickListener(x->{if(!selected.isEmpty()){toggle(c);return;}cardActions(c,number);});v.setOnLongClickListener(x->{toggle(c);return true;});return v;}
 void toggle(Card c){if(selected.contains(c.id))selected.remove(c.id);else selected.add(c.id);selectionBar.setVisibility(selected.isEmpty()?View.GONE:View.VISIBLE);selectedCount.setText(selected.size()+" selected");renderGrid();}
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 void cardActions(Card c,int number){String[]x={"Show card","Edit card","Move to Leitner box","Delete card"};new AlertDialog.Builder(this).setTitle(number+". "+c.p).setItems(x,(d,w)->{if(w==0)showCardDialog(c);else if(w==1)editDialog(c);else if(w==2)chooseBox(c);else deleteOne(c);}).setNegativeButton("Close",null).show();}
 void showCardDialog(Card c){String msg="English meaning\n"+blank(c.en)+"\n\nمعنی فارسی\n"+blank(c.fa)+"\n\nUsage\n"+blank(c.n)+"\n\nExample\n"+blank(c.e)+"\n\nLeitner Box "+box(c);new AlertDialog.Builder(this).setTitle(c.p).setMessage(msg).setPositiveButton("Edit",(d,w)->editDialog(c)).setNegativeButton("Close",null).show();}
 String blank(String s){return s==null||s.trim().isEmpty()?"—":s;}
 LinearLayout form(Card c){LinearLayout l=new LinearLayout(this);l.setPadding(dp(24),0,dp(24),0);l.setOrientation(LinearLayout.VERTICAL);String[]h={"Phrase","English meaning","معنی فارسی","Usage","Example"};String[]v=c==null?new String[]{"","","","",""}:new String[]{c.p,c.en,c.fa,c.n,c.e};for(int i=0;i<h.length;i++){EditText x=new EditText(this);x.setHint(h[i]);x.setText(v[i]);l.addView(x);}return l;}
 void editDialog(Card c){LinearLayout l=form(c);new AlertDialog.Builder(this).setTitle(c==null?"Add card to "+lang:"Edit card").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String p=((EditText)l.getChildAt(0)).getText().toString().trim();if(p.isEmpty())return;String en=((EditText)l.getChildAt(1)).getText().toString(),fa=((EditText)l.getChildAt(2)).getText().toString(),n=((EditText)l.getChildAt(3)).getText().toString(),e=((EditText)l.getChildAt(4)).getText().toString();if(c==null)cards.add(new Card("c"+System.currentTimeMillis(),lang,p,en,fa,n,e));else{c.p=p;c.en=en;c.fa=fa;c.n=n;c.e=e;}saveCustom();renderLibrary();}).show();}
 void deleteOne(Card c){new AlertDialog.Builder(this).setTitle("Delete card?").setMessage(c.p).setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{cards.remove(c);sp.edit().putBoolean(c.id+"_deleted",true).apply();saveCustom();renderLibrary();}).show();}
 void deleteSelected(){if(selected.isEmpty())return;new AlertDialog.Builder(this).setTitle("Delete "+selected.size()+" cards?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{ArrayList<Card>gone=new ArrayList<>();for(Card c:cards)if(selected.contains(c.id)){gone.add(c);sp.edit().putBoolean(c.id+"_deleted",true).apply();}cards.removeAll(gone);selected.clear();saveCustom();renderLibrary();}).show();}
 void chooseBox(Card c){String[]b={"Box 1","Box 2","Box 3","Box 4","Box 5"};new AlertDialog.Builder(this).setTitle("Move "+c.p).setSingleChoiceItems(b,box(c)-1,(d,w)->{sp.edit().putInt(c.id+"_box",w+1).apply();d.dismiss();renderLibrary();}).show();}
 void moveSelected(){if(selected.isEmpty())return;String[]b={"Box 1","Box 2","Box 3","Box 4","Box 5"};new AlertDialog.Builder(this).setTitle("Move selected cards").setItems(b,(d,w)->{SharedPreferences.Editor ed=sp.edit();for(Card c:cards)if(selected.contains(c.id))ed.putInt(c.id+"_box",w+1);ed.apply();selected.clear();renderLibrary();}).show();}
 void updateStats(){int total=0,g=0,h=0;for(Card c:cards)if(c.lang.equals(lang)){total++;if(result(c)==1)g++;else if(result(c)==-1)h++;}int u=Math.max(0,total-g-h);weight(goodBar,g);weight(hardBar,h);weight(unseenBar,u);stats.setText("Good "+g+"  •  Hard "+h+"  •  Unreviewed "+u);}
 void weight(View v,int w){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.weight=Math.max(0,w);p.width=0;v.setLayoutParams(p);}
 void showMenu(){String[]x={"Switch language","Add new language","Import CSV","Export active language to CSV","View by Leitner Box","Reset Leitner progress","Dark mode","Light mode"};new AlertDialog.Builder(this).setTitle("Menu").setItems(x,(d,w)->{if(w==0)chooseLanguage();else if(w==1)addLanguage();else if(w==2)importCsv();else if(w==3)exportCsv();else if(w==4)viewByBox();else if(w==5)resetLeitner();else if(w==6)setTheme("dark");else setTheme("light");}).show();}
 void chooseLanguage(){String[]a=decks.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Switch language").setSingleChoiceItems(a,decks.indexOf(lang),(d,w)->{lang=decks.get(w);selected.clear();search.setText("");d.dismiss();renderLibrary();}).show();}
 void addLanguage(){EditText i=new EditText(this);i.setHint("e.g. German");new AlertDialog.Builder(this).setTitle("Add new language").setView(i).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{String n=i.getText().toString().trim();if(!n.isEmpty()&&!decks.contains(n)){decks.add(n);saveDecks();lang=n;renderLibrary();}}).show();}
 void setTheme(String t){sp.edit().putString("theme",t).apply();applyTheme();recreate();}
 void viewByBox(){String[]b=new String[5];for(int k=1;k<=5;k++){int n=0;for(Card c:cards)if(c.lang.equals(lang)&&box(c)==k)n++;b[k-1]="Box "+k+"  ("+n+" cards)";}new AlertDialog.Builder(this).setTitle("Leitner Boxes — "+lang).setItems(b,(d,w)->{query="";search.setText("");renderLibrary();for(int i=0;i<cardGrid.getChildCount();i++){View v=cardGrid.getChildAt(i);v.setVisibility(View.VISIBLE);}Toast.makeText(this,"Box "+(w+1)+": tap cards to edit their box",Toast.LENGTH_LONG).show();}).show();}
 void resetLeitner(){new AlertDialog.Builder(this).setTitle("Reset Leitner progress?").setMessage("This resets all "+lang+" cards to Box 1 and clears Good/Hard status.").setNegativeButton("Cancel",null).setPositiveButton("Reset",(d,w)->{SharedPreferences.Editor ed=sp.edit();for(Card c:cards)if(c.lang.equals(lang)){ed.remove(c.id+"_box");ed.remove(c.id+"_due");ed.remove(c.id+"_result");}ed.apply();renderLibrary();}).show();}
 void startDaily(){dailyCards.clear();dailyGood=0;dailyHard=0;dailyIndex=0;long y=dayKey()-1;ArrayList<Card>h=new ArrayList<>(),o=new ArrayList<>();for(Card c:cards)if(c.lang.equals(lang)){if(sp.getLong(c.id+"_dailyHard",-99)==y)h.add(c);else o.add(c);}Collections.shuffle(o);dailyCards.addAll(h);for(Card c:o)if(dailyCards.size()<10)dailyCards.add(c);while(dailyCards.size()>10)dailyCards.remove(dailyCards.size()-1);if(dailyCards.isEmpty()){Toast.makeText(this,"No cards in "+lang,Toast.LENGTH_SHORT).show();return;}dailyMode=true;libraryView.setVisibility(View.GONE);practiceView.setVisibility(View.VISIBLE);showDaily();}
 long dayKey(){Calendar c=Calendar.getInstance();return c.get(Calendar.YEAR)*1000L+c.get(Calendar.DAY_OF_YEAR);}
 void showDaily(){if(dailyIndex>=dailyCards.size()){dailyMode=false;new AlertDialog.Builder(this).setTitle("Daily Practice Complete").setMessage("Reviewed: "+dailyCards.size()+"\n\nGood: "+dailyGood+"\nHard: "+dailyHard+"\n\nHard cards are prioritized tomorrow.").setPositiveButton("Back to Library",(d,w)->renderLibrary()).show();return;}cur=dailyCards.get(dailyIndex);practiceProgress.setText("Daily Practice  "+(dailyIndex+1)+" / "+dailyCards.size());phrase.setText(cur.p);enMeaning.setText(blank(cur.en));faMeaning.setText(blank(cur.fa));note.setText(blank(cur.n));example.setText(blank(cur.e));answerBox.setVisibility(View.GONE);rating.setVisibility(View.GONE);show.setVisibility(View.VISIBLE);studyArea.setAlpha(0f);studyArea.setTranslationX(dp(40));studyArea.animate().alpha(1f).translationX(0).setDuration(180).setInterpolator(new DecelerateInterpolator()).start();}
 void rate(boolean ok){if(cur==null)return;int b=ok?Math.min(5,box(cur)+1):1;sp.edit().putInt(cur.id+"_box",b).putLong(cur.id+"_due",System.currentTimeMillis()+interval(b)).putInt(cur.id+"_result",ok?1:-1).apply();if(ok)dailyGood++;else{dailyHard++;sp.edit().putLong(cur.id+"_dailyHard",dayKey()).apply();}dailyIndex++;showDaily();}
 void leavePractice(){new AlertDialog.Builder(this).setTitle("Leave Daily Practice?").setMessage("Your ratings so far are saved.").setNegativeButton("Stay",null).setPositiveButton("Leave",(d,w)->renderLibrary()).show();}
 void exportCsv(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"phrase_cards_"+lang.toLowerCase()+".csv");startActivityForResult(i,EXPORT_CSV);}
 void importCsv(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("text/*");startActivityForResult(i,IMPORT_CSV);}
 String esc(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK||data==null)return;try{Uri u=data.getData();if(r==EXPORT_CSV){BufferedWriter w=new BufferedWriter(new OutputStreamWriter(getContentResolver().openOutputStream(u),"UTF-8"));w.write("Phrase,English Meaning,Persian Meaning,Example\n");int count=0;for(Card x:cards)if(x.lang.equals(lang)){w.write(esc(x.p)+","+esc(x.en)+","+esc(x.fa)+","+esc(x.e)+"\n");count++;}w.close();Toast.makeText(this,count+" "+lang+" cards exported",Toast.LENGTH_LONG).show();}else{BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u),"UTF-8"));String line;boolean first=true;int count=0;while((line=br.readLine())!=null){if(line.trim().isEmpty())continue;ArrayList<String>a=parseCsv(line);if(first&&a.size()>0&&a.get(0).trim().toLowerCase().equals("phrase")){first=false;continue;}first=false;if(a.size()>=2){String p=a.get(0).trim(),en="",fa="",e="";if(a.size()>=4){en=a.get(1);fa=a.get(2);e=a.get(3);}else{String m=a.get(1);if(hasPersian(m))fa=m;else en=m;}if(!p.isEmpty()){cards.add(new Card("c"+System.currentTimeMillis()+"_"+count,lang,p,en,fa,"",e));count++;}}}br.close();saveCustom();Toast.makeText(this,count+" cards imported into "+lang,Toast.LENGTH_LONG).show();renderLibrary();}}catch(Exception e){new AlertDialog.Builder(this).setTitle("CSV error").setMessage(String.valueOf(e.getMessage())).setPositiveButton("OK",null).show();}}
 ArrayList<String>parseCsv(String s){ArrayList<String>a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='"'){b.append('"');i++;}else q=!q;}else if(c==','&&!q){a.add(b.toString());b.setLength(0);}else b.append(c);}a.add(b.toString());return a;}
}